/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

import java.util.ArrayList;
import java.util.TreeMap;
import java.util.TreeSet;
import tp.pkg5.gp14.Contacto;
import tp.pkg5.gp14.Directorio;

/**
 *
 * @author carlo
 */
public class Directorioprincipal extends javax.swing.JFrame {
 public static TreeMap<Long, Contacto> contactos = new TreeMap<>(); 
    public static ArrayList<Contacto> listaContactos= new ArrayList<>();
    public static TreeSet<Long> numeros = new TreeSet<>();
    /**
     * Creates new form Directorioprincipal
     */
    public Directorioprincipal() {
        initComponents();
        Directorio contactos = new Directorio();
        contactos.agregarContacto(2665121153L, new Contacto(15520451, "Jacinto", "Perez", "Caseros 200", "Buenos Aires"));
        contactos.agregarContacto(2665154584L, new Contacto(27127089, "Pedro", "Mayor", "Av josefa 123", "Mendoza"));
        contactos.agregarContacto(2664008530L, new Contacto(43551451, "Jose", "Martinez", "Mitre 154", "San Luis"));
        contactos.agregarContacto(2664454810L, new Contacto(98154251, "Tomas", "Aguirre", "9 Julio", "Misiones"));
        contactos.agregarContacto(2664550011L, new Contacto(39845123,"Lautaro", "Benitez", "Av Santo Ortiz","San Luis"));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenucontactos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenutablacontactos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenusalir = new javax.swing.JMenu();
        jMenuexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Directorio Principal");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel1)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(598, Short.MAX_VALUE))
        );

        jMenucontactos.setText("Agenda contactos");

        jMenuItem1.setText("Agenda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenucontactos.add(jMenuItem1);

        jMenuBar1.add(jMenucontactos);

        jMenutablacontactos.setText("Tabla de busqueda");

        jMenuItem2.setText("Tabla");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenutablacontactos.add(jMenuItem2);

        jMenuBar1.add(jMenutablacontactos);

        jMenusalir.setText("Salir");

        jMenuexit.setText("Salir");
        jMenuexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuexitActionPerformed(evt);
            }
        });
        jMenusalir.add(jMenuexit);

        jMenuBar1.add(jMenusalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        Agendadecontactos mmateria = new Agendadecontactos();
        mmateria.setVisible(true);
        escritorio.add(mmateria);
        escritorio.moveToFront(mmateria); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        escritorio.removeAll();
       escritorio.repaint();
       vistaBusqueda JTabla = new vistaBusqueda();
        JTabla.setVisible(true);
       escritorio.add(JTabla);
       escritorio.moveToFront(JTabla); 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuexitActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jMenuexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Directorioprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Directorioprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Directorioprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Directorioprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Directorioprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu jMenucontactos;
    private javax.swing.JMenuItem jMenuexit;
    private javax.swing.JMenu jMenusalir;
    private javax.swing.JMenu jMenutablacontactos;
    // End of variables declaration//GEN-END:variables
}
